-- VHDL Entity bonus3a_lib.schemas_tsest.symbol
--
-- Created:
--          by - hp.UNKNOWN (LAPTOP-RSPOQ668)
--          at - 20:51:06 18.12.2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY schemas_tsest IS
   PORT( 
      din0 : IN     std_logic;
      pre  : IN     std_logic;
      dout : OUT    std_logic
   );

-- Declarations

END schemas_tsest ;

--
-- VHDL Architecture bonus3a_lib.schemas_tsest.flow
--
-- Created:
--          by - hp.UNKNOWN (LAPTOP-RSPOQ668)
--          at - 20:51:06 18.12.2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
ARCHITECTURE flow OF schemas_tsest IS

BEGIN

   -----------------------------------------------------------------
   process0_proc : PROCESS
   -----------------------------------------------------------------
   BEGIN
      din0 <= '1';
      wait;
   END PROCESS process0_proc;

   -----------------------------------------------------------------
   clock_proc : PROCESS
   -----------------------------------------------------------------
   BEGIN
      wait until clk = '1';
      clk <= '1';
      wait on clk until clk = '0';
      clk <= '0';
      wait until clk = '1';
      clk <= '1';
      wait on clk until clk = '0';
      clk <= '0';
      wait on clk until clk = '0';
      clk <= '0';
      wait on clk until clk = '0';
      clk <= '0';
   END PROCESS clock_proc;


END flow;
