-- VHDL Entity bonus3a_lib.schemas_tsest.symbol
--
-- Created:
--          by - hp.UNKNOWN (LAPTOP-RSPOQ668)
--          at - 20:26:34 18.12.2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY schemas_tsest IS
   PORT( 
      din0 : IN     std_logic;
      pre  : IN     std_logic;
      dout : OUT    std_logic
   );

-- Declarations

END schemas_tsest ;

--
-- VHDL Architecture bonus3a_lib.schemas_tsest.fsm
--
-- Created:
--          by - hp.UNKNOWN (LAPTOP-RSPOQ668)
--          at - 20:26:34 18.12.2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
 
ARCHITECTURE fsm OF schemas_tsest IS

   TYPE STATE_TYPE IS (
      s0,
      s1,
      s2,
      s3,
      s4,
      s5,
      s6
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      clk,
      rst
   )
   -----------------------------------------------------------------
   BEGIN
      IF (rst = '0') THEN
         current_state <= s0;
      ELSIF (clk'EVENT AND clk = '1') THEN
         current_state <= next_state;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      current_state
   )
   -----------------------------------------------------------------
   BEGIN
      CASE current_state IS
         WHEN s0 => 
            IF ('1') THEN 
               next_state <= s1;
            ELSE
               next_state <= s0;
            END IF;
         WHEN s1 => 
            IF ('0') THEN 
               next_state <= s2;
            ELSIF ('1') THEN 
               next_state <= s1;
            ELSE
               next_state <= s1;
            END IF;
         WHEN s2 => 
            IF ('1') THEN 
               next_state <= s3;
            ELSIF ('0') THEN 
               next_state <= s0;
            ELSE
               next_state <= s2;
            END IF;
         WHEN s3 => 
            IF ('0') THEN 
               next_state <= s4;
            ELSIF ('1') THEN 
               next_state <= s1;
            ELSIF ('1') THEN 
               next_state <= s1;
            ELSE
               next_state <= s3;
            END IF;
         WHEN s4 => 
            IF ('0') THEN 
               next_state <= s5;
            ELSIF ('1') THEN 
               next_state <= s3;
            ELSE
               next_state <= s4;
            END IF;
         WHEN s5 => 
            IF ('0') THEN 
               next_state <= s6;
            ELSIF ('1') THEN 
               next_state <= s1;
            ELSE
               next_state <= s5;
            END IF;
         WHEN s6 => 
            IF ('0') THEN 
               next_state <= s0;
            ELSIF ('1') THEN 
               next_state <= s1;
            ELSE
               next_state <= s6;
            END IF;
         WHEN OTHERS =>
            next_state <= s0;
      END CASE;
   END PROCESS nextstate_proc;
 
END fsm;
